import Foundation

/// One source of truth for every solo and exact-face ladder, including preview.
enum SameFaceCatalog {
    static let rulesetVersion = 2
    static let all: [ComboDef] = [
        ComboDef(id: "sf_arrow1_1", name: "Quick Shot", owner: "archer", source: .weapon, required: [ComboIngredient(.exact(.arrow1), 1)], damage: 8, flavor: "D8."),
        ComboDef(id: "sf_arrow1_2", name: "Twin Shot", owner: "archer", source: .weapon, required: [ComboIngredient(.exact(.arrow1), 2)], damage: 18, markPercent: 20, flavor: "D18; M20."),
        ComboDef(id: "sf_arrow1_3", name: "Hunter's Volley", owner: "archer", source: .weapon, required: [ComboIngredient(.exact(.arrow1), 3)], damage: 30, markPercent: 25, flavor: "D30; M25."),
        ComboDef(id: "sf_arrow1_4", name: "Storm of Shafts", owner: "archer", source: .weapon, required: [ComboIngredient(.exact(.arrow1), 4)], damage: 44, markPercent: 25, splashDamage: 10, flavor: "D44; M25; splash 10."),
        ComboDef(id: "sf_arrow1_5", name: "Rain of Arrows", owner: "archer", source: .weapon, required: [ComboIngredient(.exact(.arrow1), 5)], damage: 60, markPercent: 30, splashDamage: 16, flavor: "D60; M30; splash 16."),
        ComboDef(id: "sf_arrow1_6", name: "Skyfall Volley", owner: "archer", source: .weapon, required: [ComboIngredient(.exact(.arrow1), 6)], damage: 78, markPercent: 35, splashDamage: 24, flavor: "D78; M35; splash 24."),
        ComboDef(id: "sf_arrow2_1", name: "Piercing Shot", owner: "archer", source: .weapon, required: [ComboIngredient(.exact(.arrow2), 1)], damage: 10, pierce: 0.2, flavor: "D10; X20."),
        ComboDef(id: "sf_arrow2_2", name: "Piercing Bolt", owner: "archer", source: .weapon, required: [ComboIngredient(.exact(.arrow2), 2)], damage: 22, pierce: 0.3, flavor: "D22; X30."),
        ComboDef(id: "sf_arrow2_3", name: "Armourbreaker", owner: "archer", source: .weapon, required: [ComboIngredient(.exact(.arrow2), 3)], damage: 36, pierce: 0.4, flavor: "D36; X40."),
        ComboDef(id: "sf_arrow2_4", name: "Siege Bolt", owner: "archer", source: .weapon, required: [ComboIngredient(.exact(.arrow2), 4)], damage: 52, pierce: 0.5, weaken: 0.2, flavor: "D52; X50; W20."),
        ComboDef(id: "sf_arrow2_5", name: "King's Bane", owner: "archer", source: .weapon, required: [ComboIngredient(.exact(.arrow2), 5)], damage: 70, pierce: 0.6, weaken: 0.25, flavor: "D70; X60; W25."),
        ComboDef(id: "sf_arrow2_6", name: "Horizon Splitter", owner: "archer", source: .weapon, required: [ComboIngredient(.exact(.arrow2), 6)], damage: 90, pierce: 0.75, weaken: 0.3, flavor: "D90; X75; W30."),
        ComboDef(id: "sf_arrow3_1", name: "Heavy Shot", owner: "archer", source: .weapon, required: [ComboIngredient(.exact(.arrow3), 1)], damage: 12, flavor: "D12."),
        ComboDef(id: "sf_arrow3_2", name: "Deadeye", owner: "archer", source: .weapon, required: [ComboIngredient(.exact(.arrow3), 2)], damage: 27, pierce: 0.15, flavor: "D27; X15."),
        ComboDef(id: "sf_arrow3_3", name: "Perfect Shot", owner: "archer", source: .weapon, required: [ComboIngredient(.exact(.arrow3), 3)], damage: 45, pierce: 0.25, flavor: "D45; X25."),
        ComboDef(id: "sf_arrow3_4", name: "Execution Shot", owner: "archer", source: .weapon, required: [ComboIngredient(.exact(.arrow3), 4)], damage: 64, pierce: 0.3, conditionalDamagePercent: 15, damageCondition: "marked", flavor: "D64; X30; +15% damage if target was Marked."),
        ComboDef(id: "sf_arrow3_5", name: "Royal Execution", owner: "archer", source: .weapon, required: [ComboIngredient(.exact(.arrow3), 5)], damage: 85, pierce: 0.4, conditionalDamagePercent: 20, damageCondition: "marked", flavor: "D85; X40; +20% damage if target was Marked."),
        ComboDef(id: "sf_arrow3_6", name: "The Last Arrow", owner: "archer", source: .weapon, required: [ComboIngredient(.exact(.arrow3), 6)], damage: 108, pierce: 0.5, conditionalDamagePercent: 25, damageCondition: "marked", flavor: "D108; X50; +25% damage if target was Marked."),
        ComboDef(id: "sf_bowSmack_1", name: "Bow Smack", owner: "archer", source: .weapon, required: [ComboIngredient(.exact(.bowSmack), 1)], damage: 5, weaken: 0.15, flavor: "D5; W15."),
        ComboDef(id: "sf_bowSmack_2", name: "Point-Blank", owner: "archer", source: .weapon, required: [ComboIngredient(.exact(.bowSmack), 2)], damage: 12, shield: 6, weaken: 0.2, flavor: "D12; S6; W20."),
        ComboDef(id: "sf_bowSmack_3", name: "Break Contact", owner: "archer", source: .weapon, required: [ComboIngredient(.exact(.bowSmack), 3)], damage: 21, shield: 10, weaken: 0.25, flavor: "D21; S10; W25."),
        ComboDef(id: "sf_bowSmack_4", name: "Turning Strike", owner: "archer", source: .weapon, required: [ComboIngredient(.exact(.bowSmack), 4)], damage: 32, shield: 14, weaken: 0.3, flavor: "D32; S14; W30."),
        ComboDef(id: "sf_bowSmack_5", name: "Bowguard Assault", owner: "archer", source: .weapon, required: [ComboIngredient(.exact(.bowSmack), 5)], damage: 45, shield: 18, weaken: 0.35, flavor: "D45; S18; W35."),
        ComboDef(id: "sf_bowSmack_6", name: "Unbroken Bow", owner: "archer", source: .weapon, required: [ComboIngredient(.exact(.bowSmack), 6)], damage: 60, shield: 24, dodgeCharges: 1, weaken: 0.4, flavor: "D60; S24; W40; Q1."),
        ComboDef(id: "sf_overhead_1", name: "Overhead", owner: "warrior", source: .weapon, required: [ComboIngredient(.exact(.overhead), 1)], damage: 12, flavor: "D12."),
        ComboDef(id: "sf_overhead_2", name: "Crushing Blow", owner: "warrior", source: .weapon, required: [ComboIngredient(.exact(.overhead), 2)], damage: 27, flavor: "D27."),
        ComboDef(id: "sf_overhead_3", name: "Earthshaker", owner: "warrior", source: .weapon, required: [ComboIngredient(.exact(.overhead), 3)], damage: 44, weaken: 0.2, flavor: "D44; W20."),
        ComboDef(id: "sf_overhead_4", name: "Warlord's Answer", owner: "warrior", source: .weapon, required: [ComboIngredient(.exact(.overhead), 4)], damage: 62, shield: 10, weaken: 0.25, flavor: "D62; S10; W25."),
        ComboDef(id: "sf_overhead_5", name: "Thronebreaker", owner: "warrior", source: .weapon, required: [ComboIngredient(.exact(.overhead), 5)], damage: 83, shield: 14, weaken: 0.3, flavor: "D83; S14; W30."),
        ComboDef(id: "sf_overhead_6", name: "Judgement of Steel", owner: "warrior", source: .weapon, required: [ComboIngredient(.exact(.overhead), 6)], damage: 106, shield: 18, pierce: 0.3, weaken: 0.35, flavor: "D106; S18; W35; X30."),
        ComboDef(id: "sf_sideSwing_1", name: "Side Swing", owner: "warrior", source: .weapon, required: [ComboIngredient(.exact(.sideSwing), 1)], damage: 9, flavor: "D9."),
        ComboDef(id: "sf_sideSwing_2", name: "Wide Sweep", owner: "warrior", source: .weapon, required: [ComboIngredient(.exact(.sideSwing), 2)], damage: 20, splashDamage: 6, flavor: "D20; splash 6."),
        ComboDef(id: "sf_sideSwing_3", name: "Cleaving Arc", owner: "warrior", source: .weapon, required: [ComboIngredient(.exact(.sideSwing), 3)], damage: 33, splashDamage: 11, flavor: "D33; splash 11."),
        ComboDef(id: "sf_sideSwing_4", name: "Whirlwind Crush", owner: "warrior", source: .weapon, required: [ComboIngredient(.exact(.sideSwing), 4)], damage: 48, weaken: 0.2, splashDamage: 18, flavor: "D48; splash 18; W20 on primary."),
        ComboDef(id: "sf_sideSwing_5", name: "Blood Tide", owner: "warrior", source: .weapon, required: [ComboIngredient(.exact(.sideSwing), 5)], damage: 65, lifesteal: true, splashDamage: 26, lifestealCap: 10, flavor: "D65; splash 26; heal 20% of native HP damage dealt, maximum 10."),
        ComboDef(id: "sf_sideSwing_6", name: "Last Stand", owner: "warrior", source: .weapon, required: [ComboIngredient(.exact(.sideSwing), 6)], damage: 84, weaken: 0.25, lifesteal: true, splashDamage: 36, lifestealCap: 14, flavor: "D84; splash 36; heal 20% of native HP damage dealt, maximum 14; W25 on primary."),
        ComboDef(id: "sf_swiftSlash_1", name: "Swift Slash", owner: "rogue", source: .weapon, required: [ComboIngredient(.exact(.swiftSlash), 1)], damage: 7, flavor: "D7."),
        ComboDef(id: "sf_swiftSlash_2", name: "Flurry", owner: "rogue", source: .weapon, required: [ComboIngredient(.exact(.swiftSlash), 2)], damage: 16, bleedAmount: 3, bleedTurns: 2, flavor: "D16; L3."),
        ComboDef(id: "sf_swiftSlash_3", name: "Thousand Cuts", owner: "rogue", source: .weapon, required: [ComboIngredient(.exact(.swiftSlash), 3)], damage: 27, bleedAmount: 5, bleedTurns: 2, flavor: "D27; L5."),
        ComboDef(id: "sf_swiftSlash_4", name: "Veiled Assault", owner: "rogue", source: .weapon, required: [ComboIngredient(.exact(.swiftSlash), 4)], damage: 40, dodgeCharges: 1, bleedAmount: 6, bleedTurns: 2, flavor: "D40; L6; Q1."),
        ComboDef(id: "sf_swiftSlash_5", name: "Nightfall Ambush", owner: "rogue", source: .weapon, required: [ComboIngredient(.exact(.swiftSlash), 5)], damage: 55, dodgeCharges: 1, bleedAmount: 8, bleedTurns: 2, markPercent: 20, flavor: "D55; L8; Q1; M20."),
        ComboDef(id: "sf_swiftSlash_6", name: "Vanishing Strike", owner: "rogue", source: .weapon, required: [ComboIngredient(.exact(.swiftSlash), 6)], damage: 72, dodgeCharges: 2, bleedAmount: 10, bleedTurns: 2, markPercent: 25, flavor: "D72; L10; Q2; M25."),
        ComboDef(id: "sf_daggerThrow_1", name: "Dagger Throw", owner: "rogue", source: .weapon, required: [ComboIngredient(.exact(.daggerThrow), 1)], damage: 9, bleedAmount: 2, bleedTurns: 2, flavor: "D9; L2."),
        ComboDef(id: "sf_daggerThrow_2", name: "Twin Fang", owner: "rogue", source: .weapon, required: [ComboIngredient(.exact(.daggerThrow), 2)], damage: 20, bleedAmount: 4, bleedTurns: 2, flavor: "D20; L4."),
        ComboDef(id: "sf_daggerThrow_3", name: "Hemorrhage", owner: "rogue", source: .weapon, required: [ComboIngredient(.exact(.daggerThrow), 3)], damage: 33, bleedAmount: 6, bleedTurns: 2, conditionalDamagePercent: 15, damageCondition: "bleeding", flavor: "D33; L6; +15% damage against a target already Bleeding."),
        ComboDef(id: "sf_daggerThrow_4", name: "Red Horizon", owner: "rogue", source: .weapon, required: [ComboIngredient(.exact(.daggerThrow), 4)], damage: 48, bleedAmount: 7, bleedTurns: 2, conditionalDamagePercent: 20, damageCondition: "bleeding", flavor: "D48; L7; +20% damage against a target already Bleeding."),
        ComboDef(id: "sf_daggerThrow_5", name: "Death's Reach", owner: "rogue", source: .weapon, required: [ComboIngredient(.exact(.daggerThrow), 5)], damage: 65, bleedAmount: 8, bleedTurns: 2, earlyTick: "bleed", flavor: "D65; L8; one early Bleed tick after application."),
        ComboDef(id: "sf_daggerThrow_6", name: "The Final Fang", owner: "rogue", source: .weapon, required: [ComboIngredient(.exact(.daggerThrow), 6)], damage: 84, bleedAmount: 10, bleedTurns: 2, pierce: 0.3, earlyTick: "bleed", flavor: "D84; L10; one early Bleed tick after application; X30."),
        ComboDef(id: "sf_poison_1", name: "Venom", owner: "rogue", source: .weapon, required: [ComboIngredient(.exact(.poison), 1)], poisonAmount: 2, flavor: "P2."),
        ComboDef(id: "sf_poison_2", name: "Coated Edge", owner: "rogue", source: .weapon, required: [ComboIngredient(.exact(.poison), 2)], poisonAmount: 3, weaken: 0.15, flavor: "P3; W15."),
        ComboDef(id: "sf_poison_3", name: "Creeping Death", owner: "rogue", source: .weapon, required: [ComboIngredient(.exact(.poison), 3)], poisonAmount: 4, weaken: 0.2, flavor: "P4; W20."),
        ComboDef(id: "sf_poison_4", name: "Withering Touch", owner: "rogue", source: .weapon, required: [ComboIngredient(.exact(.poison), 4)], shield: 10, poisonAmount: 5, weaken: 0.25, flavor: "P5; W25; S10."),
        ComboDef(id: "sf_poison_5", name: "Serpent's Dance", owner: "rogue", source: .weapon, required: [ComboIngredient(.exact(.poison), 5)], shield: 16, dodgeCharges: 1, poisonAmount: 6, weaken: 0.3, flavor: "P6; W30; S16; Q1."),
        ComboDef(id: "sf_poison_6", name: "Death by Inches", owner: "rogue", source: .weapon, required: [ComboIngredient(.exact(.poison), 6)], shield: 22, dodgeCharges: 1, poisonAmount: 8, weaken: 0.35, earlyTick: "poison", flavor: "P8; W35; S22; Q1; one early Poison tick after application."),
        ComboDef(id: "sf_runeFire_1", name: "Ember", owner: "magician", source: .weapon, required: [ComboIngredient(.exact(.runeFire), 1)], damage: 7, burnAmount: 1, flavor: "D7; B1."),
        ComboDef(id: "sf_runeFire_2", name: "Fireball", owner: "magician", source: .weapon, required: [ComboIngredient(.exact(.runeFire), 2)], damage: 17, burnAmount: 3, flavor: "D17; B3."),
        ComboDef(id: "sf_runeFire_3", name: "Meteor", owner: "magician", source: .weapon, required: [ComboIngredient(.exact(.runeFire), 3)], damage: 30, burnAmount: 4, flavor: "D30; B4."),
        ComboDef(id: "sf_runeFire_4", name: "Inferno", owner: "magician", source: .weapon, required: [ComboIngredient(.exact(.runeFire), 4)], damage: 45, burnAmount: 6, splashDamage: 10, flavor: "D45; B6; splash 10."),
        ComboDef(id: "sf_runeFire_5", name: "Phoenix Fire", owner: "magician", source: .weapon, required: [ComboIngredient(.exact(.runeFire), 5)], damage: 62, heal: 8, burnAmount: 8, splashDamage: 16, flavor: "D62; B8; splash 16; H8."),
        ComboDef(id: "sf_runeFire_6", name: "Sunfall", owner: "magician", source: .weapon, required: [ComboIngredient(.exact(.runeFire), 6)], damage: 81, heal: 12, burnAmount: 10, splashDamage: 24, flavor: "D81; B10; splash 24; H12."),
        ComboDef(id: "sf_runeFrost_1", name: "Frost Ward", owner: "magician", source: .weapon, required: [ComboIngredient(.exact(.runeFrost), 1)], damage: 4, shield: 5, weaken: 0.1, flavor: "D4; S5; W10."),
        ComboDef(id: "sf_runeFrost_2", name: "Ice Blast", owner: "magician", source: .weapon, required: [ComboIngredient(.exact(.runeFrost), 2)], damage: 10, shield: 10, weaken: 0.2, flavor: "D10; S10; W20."),
        ComboDef(id: "sf_runeFrost_3", name: "Glacier", owner: "magician", source: .weapon, required: [ComboIngredient(.exact(.runeFrost), 3)], damage: 18, shield: 16, weaken: 0.3, delaysEnemy: true, flavor: "D18; S16; W30; delay one pending action."),
        ComboDef(id: "sf_runeFrost_4", name: "Glacial Passage", owner: "magician", source: .weapon, required: [ComboIngredient(.exact(.runeFrost), 4)], damage: 28, shield: 23, weaken: 0.35, delaysEnemy: true, flavor: "D28; S23; W35; delay one pending action."),
        ComboDef(id: "sf_runeFrost_5", name: "Winter Bastion", owner: "magician", source: .weapon, required: [ComboIngredient(.exact(.runeFrost), 5)], damage: 40, shield: 31, weaken: 0.4, delaysEnemy: true, flavor: "D40; S31; W40; delay one pending action."),
        ComboDef(id: "sf_runeFrost_6", name: "Stillness of the Duat", owner: "magician", source: .weapon, required: [ComboIngredient(.exact(.runeFrost), 6)], damage: 54, shield: 40, weaken: 0.5, delaysEnemy: true, flavor: "D54; S40; W50; delay one pending action."),
        ComboDef(id: "sf_runeLife_1", name: "Mend", owner: "magician", source: .armor, required: [ComboIngredient(.exact(.runeLife), 1)], heal: 7, flavor: "H7."),
        ComboDef(id: "sf_runeLife_2", name: "Mending Bloom", owner: "magician", source: .armor, required: [ComboIngredient(.exact(.runeLife), 2)], heal: 15, regenAmount: 2, regenTurns: 2, flavor: "H15; R2."),
        ComboDef(id: "sf_runeLife_3", name: "Sanctuary", owner: "magician", source: .armor, required: [ComboIngredient(.exact(.runeLife), 3)], heal: 24, shield: 8, regenAmount: 3, regenTurns: 2, flavor: "H24; S8; R3."),
        ComboDef(id: "sf_runeLife_4", name: "Wellspring", owner: "magician", source: .armor, required: [ComboIngredient(.exact(.runeLife), 4)], heal: 34, shield: 14, regenAmount: 4, regenTurns: 2, flavor: "H34; S14; R4."),
        ComboDef(id: "sf_runeLife_5", name: "Phoenix Rite", owner: "magician", source: .armor, required: [ComboIngredient(.exact(.runeLife), 5)], heal: 45, shield: 20, regenAmount: 5, regenTurns: 2, cleanseCount: 1, flavor: "H45; S20; R5; C1."),
        ComboDef(id: "sf_runeLife_6", name: "Garden of Eternity", owner: "magician", source: .armor, required: [ComboIngredient(.exact(.runeLife), 6)], heal: 57, shield: 28, regenAmount: 6, regenTurns: 2, cleanseCount: 99, flavor: "H57; S28; R6; Call."),
        ComboDef(id: "sf_runeArcane_1", name: "Arcane Dart", owner: "magician", source: .weapon, required: [ComboIngredient(.exact(.runeArcane), 1)], damage: 9, pierce: 0.2, flavor: "D9; X20."),
        ComboDef(id: "sf_runeArcane_2", name: "Arcane Barrage", owner: "magician", source: .weapon, required: [ComboIngredient(.exact(.runeArcane), 2)], damage: 21, pierce: 0.3, flavor: "D21; X30."),
        ComboDef(id: "sf_runeArcane_3", name: "Arcane Storm", owner: "magician", source: .weapon, required: [ComboIngredient(.exact(.runeArcane), 3)], damage: 35, pierce: 0.4, markPercent: 20, flavor: "D35; X40; M20."),
        ComboDef(id: "sf_runeArcane_4", name: "Astral Lance", owner: "magician", source: .weapon, required: [ComboIngredient(.exact(.runeArcane), 4)], damage: 51, pierce: 0.5, markPercent: 25, flavor: "D51; X50; M25."),
        ComboDef(id: "sf_runeArcane_5", name: "Astral Reversal", owner: "magician", source: .weapon, required: [ComboIngredient(.exact(.runeArcane), 5)], damage: 69, shield: 10, pierce: 0.6, markPercent: 30, flavor: "D69; X60; M30; S10."),
        ComboDef(id: "sf_runeArcane_6", name: "The Final Word", owner: "magician", source: .weapon, required: [ComboIngredient(.exact(.runeArcane), 6)], damage: 89, shield: 16, pierce: 0.75, markPercent: 35, flavor: "D89; X75; M35; S16."),
        ComboDef(id: "sf_wandZap_1", name: "Spark", owner: "magician", source: .weapon, required: [ComboIngredient(.exact(.wandZap), 1)], damage: 8, flavor: "D8."),
        ComboDef(id: "sf_wandZap_2", name: "Chain Spark", owner: "magician", source: .weapon, required: [ComboIngredient(.exact(.wandZap), 2)], damage: 18, splashDamage: 5, flavor: "D18; splash 5."),
        ComboDef(id: "sf_wandZap_3", name: "Stormcall", owner: "magician", source: .weapon, required: [ComboIngredient(.exact(.wandZap), 3)], damage: 30, weaken: 0.15, splashDamage: 10, flavor: "D30; splash 10; W15 on primary."),
        ComboDef(id: "sf_wandZap_4", name: "Thunderchain", owner: "magician", source: .weapon, required: [ComboIngredient(.exact(.wandZap), 4)], damage: 44, weaken: 0.2, splashDamage: 16, flavor: "D44; splash 16; W20 on primary."),
        ComboDef(id: "sf_wandZap_5", name: "Tempest", owner: "magician", source: .weapon, required: [ComboIngredient(.exact(.wandZap), 5)], damage: 60, weaken: 0.25, splashDamage: 23, flavor: "D60; splash 23; W25 on primary."),
        ComboDef(id: "sf_wandZap_6", name: "Sky Unbound", owner: "magician", source: .weapon, required: [ComboIngredient(.exact(.wandZap), 6)], damage: 78, weaken: 0.3, splashDamage: 31, flavor: "D78; splash 31; W30 on primary."),
        ComboDef(id: "sf_channel_1", name: "Channel", owner: "magician", source: .armor, required: [ComboIngredient(.exact(.channel), 1)], shield: 4, focusPercent: 25, flavor: "S4; F25."),
        ComboDef(id: "sf_channel_2", name: "Deep Channel", owner: "magician", source: .armor, required: [ComboIngredient(.exact(.channel), 2)], shield: 9, focusPercent: 40, flavor: "S9; F40."),
        ComboDef(id: "sf_channel_3", name: "Runic Ward", owner: "magician", source: .armor, required: [ComboIngredient(.exact(.channel), 3)], shield: 15, focusPercent: 55, flavor: "S15; F55."),
        ComboDef(id: "sf_channel_4", name: "Prism Ward", owner: "magician", source: .armor, required: [ComboIngredient(.exact(.channel), 4)], shield: 22, dodgeCharges: 1, focusPercent: 70, flavor: "S22; F70; Q1."),
        ComboDef(id: "sf_channel_5", name: "Solar Aegis", owner: "magician", source: .armor, required: [ComboIngredient(.exact(.channel), 5)], shield: 30, dodgeCharges: 1, focusPercent: 85, cleanseCount: 1, flavor: "S30; F85; Q1; C1."),
        ComboDef(id: "sf_channel_6", name: "Astral Covenant", owner: "magician", source: .armor, required: [ComboIngredient(.exact(.channel), 6)], shield: 40, dodgeCharges: 2, focusPercent: 100, cleanseCount: 1, flavor: "S40; F100; Q2; C1."),
        ComboDef(id: "sf_block_1", name: "Block", owner: nil, source: .armor, required: [ComboIngredient(.exact(.block), 1)], shield: 8, flavor: "S8."),
        ComboDef(id: "sf_block_2", name: "Brace", owner: nil, source: .armor, required: [ComboIngredient(.exact(.block), 2)], shield: 18, flavor: "S18."),
        ComboDef(id: "sf_block_3", name: "Bulwark", owner: nil, source: .armor, required: [ComboIngredient(.exact(.block), 3)], shield: 30, reflect: 0.5, reflectCap: 8, flavor: "S30; arm one retaliation for 50% of shield absorbed by the next hit, maximum 8 damage."),
        ComboDef(id: "sf_block_4", name: "Iron Wall", owner: nil, source: .armor, required: [ComboIngredient(.exact(.block), 4)], shield: 43, reflect: 0.5, reflectCap: 12, flavor: "S43; same retaliation, maximum 12."),
        ComboDef(id: "sf_block_5", name: "Fortress", owner: nil, source: .armor, required: [ComboIngredient(.exact(.block), 5)], shield: 57, reflect: 0.5, reflectCap: 16, flavor: "S57; same retaliation, maximum 16."),
        ComboDef(id: "sf_block_6", name: "Unbroken Gate", owner: nil, source: .armor, required: [ComboIngredient(.exact(.block), 6)], shield: 72, reflect: 0.5, cleanseCount: 1, reflectCap: 20, flavor: "S72; same retaliation, maximum 20; C1."),
        ComboDef(id: "sf_evade_1", name: "Sidestep", owner: nil, source: .armor, required: [ComboIngredient(.exact(.evade), 1)], dodgeCharges: 1, flavor: "Q1."),
        ComboDef(id: "sf_evade_2", name: "Disengage", owner: nil, source: .armor, required: [ComboIngredient(.exact(.evade), 2)], shield: 3, dodgeCharges: 2, flavor: "Q2; S3."),
        ComboDef(id: "sf_evade_3", name: "Shadowstep", owner: nil, source: .armor, required: [ComboIngredient(.exact(.evade), 3)], shield: 6, dodgeCharges: 3, markPercent: 20, flavor: "Q3; S6; M20 on one chosen foe."),
        ComboDef(id: "sf_evade_4", name: "Ghostwalk", owner: nil, source: .armor, required: [ComboIngredient(.exact(.evade), 4)], shield: 10, dodgeCharges: 4, markPercent: 25, flavor: "Q4; S10; M25 on one chosen foe."),
        ComboDef(id: "sf_evade_5", name: "Phantom Dance", owner: nil, source: .armor, required: [ComboIngredient(.exact(.evade), 5)], shield: 15, dodgeCharges: 5, markPercent: 30, cleanseCount: 1, flavor: "Q5; S15; M30 on one chosen foe; C1."),
        ComboDef(id: "sf_evade_6", name: "Beyond Reach", owner: nil, source: .armor, required: [ComboIngredient(.exact(.evade), 6)], shield: 21, dodgeCharges: 6, markPercent: 35, cleanseCount: 99, flavor: "Q6; S21; M35 on one chosen foe; Call."),
        ComboDef(id: "sf_heal_1", name: "Field Dressing", owner: nil, source: .armor, required: [ComboIngredient(.exact(.heal), 1)], heal: 8, flavor: "H8."),
        ComboDef(id: "sf_heal_2", name: "Patch Up", owner: nil, source: .armor, required: [ComboIngredient(.exact(.heal), 2)], heal: 17, flavor: "H17."),
        ComboDef(id: "sf_heal_3", name: "Second Wind", owner: nil, source: .armor, required: [ComboIngredient(.exact(.heal), 3)], heal: 27, cleanseCount: 1, flavor: "H27; C1."),
        ComboDef(id: "sf_heal_4", name: "Rally", owner: nil, source: .armor, required: [ComboIngredient(.exact(.heal), 4)], heal: 38, shield: 6, cleanseCount: 1, flavor: "H38; S6; C1."),
        ComboDef(id: "sf_heal_5", name: "Renewed Vigor", owner: nil, source: .armor, required: [ComboIngredient(.exact(.heal), 5)], heal: 50, shield: 12, cleanseCount: 99, flavor: "H50; S12; Call."),
        ComboDef(id: "sf_heal_6", name: "Refuse the Grave", owner: nil, source: .armor, required: [ComboIngredient(.exact(.heal), 6)], heal: 63, shield: 20, cleanseCount: 99, flavor: "H63; S20; Call."),
        ComboDef(id: "sf_focus_1", name: "Focus", owner: nil, source: .armor, required: [ComboIngredient(.exact(.focus), 1)], focusPercent: 50, flavor: "F50."),
        ComboDef(id: "sf_focus_2", name: "Steady Aim", owner: nil, source: .armor, required: [ComboIngredient(.exact(.focus), 2)], focusPercent: 65, flavor: "F65."),
        ComboDef(id: "sf_focus_3", name: "Perfect Preparation", owner: nil, source: .armor, required: [ComboIngredient(.exact(.focus), 3)], shield: 4, focusPercent: 80, flavor: "F80; S4."),
        ComboDef(id: "sf_focus_4", name: "Battle Trance", owner: nil, source: .armor, required: [ComboIngredient(.exact(.focus), 4)], shield: 8, focusPercent: 95, flavor: "F95; S8."),
        ComboDef(id: "sf_focus_5", name: "Unshakable Intent", owner: nil, source: .armor, required: [ComboIngredient(.exact(.focus), 5)], shield: 12, focusPercent: 110, flavor: "F110; S12."),
        ComboDef(id: "sf_focus_6", name: "Moment of Destiny", owner: nil, source: .armor, required: [ComboIngredient(.exact(.focus), 6)], shield: 16, focusPercent: 125, cleanseCount: 1, flavor: "F125; S16; C1."),
    ]
    static func palette(for classID: String) -> [FaceKind] {
        switch classID {
        case "archer": return [.arrow1, .arrow2, .arrow3, .bowSmack, .block, .evade, .heal, .focus]
        case "warrior": return [.overhead, .sideSwing, .block, .heal, .focus]
        case "rogue": return [.swiftSlash, .daggerThrow, .poison, .block, .evade, .heal, .focus]
        default: return [.runeFire, .runeFrost, .runeLife, .runeArcane, .wandZap, .channel]
        }
    }
    static func action(_ face: FaceKind, count: Int) -> ComboDef? {
        let face = face == .energize ? FaceKind.focus : face
        return all.first { $0.id == "sf_\(face.rawValue)_\(count)" }
    }
    static func actions(for classID: String) -> [ComboDef] {
        palette(for: classID).flatMap { face in (1...6).compactMap { action(face, count: $0) } }
    }
    static func maximumGroup(_ face: FaceKind, dice: [Die]) -> Int {
        min(6, dice.filter { $0.faces.contains { $0.kind == face } }.count)
    }
}
